#!/usr/bin/bash

#test if savapage has opened the ports
while :
do
    Test=$(netstat -tlpn | grep 0:8632)
    if [ "$Test" ];then
        break
    fi
    # debug for arm, wait a looong time
    if [ "$count" == 48 ]; then
       echo "we cannot wait more for savapage"
       exit 1
    fi
    sleep 5
    let "count++"
done

# sync AD/LDAP users
/opt/savapage/server/bin/linux-armv7l/savapage-cmd --sync-users-and-groups
