#!/bin/bash

# check if db has to be created

createdb=false
su - postgres -c "psql -lqt | cut -d \| -f 1 | grep -q -w savapage"
if [ $? -eq 1 ]; then
   createdb=true
fi

# create db, role and set privilges

su - postgres -c "psql -c \"CREATE USER savapage WITH PASSWORD '$(cat /var/lib/nethserver/secrets/savapage)';\""
su - postgres -c "psql -c \"ALTER USER savapage WITH PASSWORD '$(cat /var/lib/nethserver/secrets/savapage)';\""
su - postgres -c "createdb -O savapage -E UTF8 -T template0 savapage"
su - postgres -c "psql -c \"grant all privileges on database savapage to savapage;\""

# savapage install when not installed already


# expand-template for writing password to server.properties which is needed by db-init
expand-template /opt/savapage/server/server.properties

# initialize db, only done when created

if [ "$createdb" = true ]; then
   su savapage -c "/opt/savapage/server/bin/linux-armv7l/savapage-db --db-init"
fi
